// Version
pragma solidity ^0.4.2;

// imports the token that is going to be sold
import "./MahdiToken.sol";

//declare contract
contract MahdiTokenSale {
	// state var to keep track of admin account
	address admin; 

	//state var of contract data type
	MahdiToken public tokenContract;

	// state var is public and is generated by solidity
	uint256 public tokenPrice;


	//constructor
	function MahdiTokenSale(MahdiToken _tokenContract, uint256 _tokenPrice) public {
		// assign the admin account to the person deploying the contract
		admin = msg.sender;
		// assign Token contract, so we can purchase tokens from admin
		tokenContract = _tokenContract;
		tokenPrice = _tokenPrice;

		// set the token price 
	}


}